### ISSUE TITLE
Scaffold out Project

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#1]
### Current Status
The project is blank. Determine project structure and set it up.

### TODO
- [x] Determine languages to use for the project
- [x] Determine tools to use for the project
- [x] Find template or build out template for the project with everything working
- [ ] Bring in leaflet, display a simple map with a simple basemap

**Comment by GeoffreyXue** [comment]
Structure :
- Google Sheets + Google Reattime Database for backend, map will pull info from the backend.
- Website hosted on Github pages
- Typescript + React for project
