### ISSUE TITLE
Feature: App Script Auto-Mailing, Sheet Filtering

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#14]
Brief: A few separate features rolled into one issue. Implementation time 4-6 hours

### Current State
The current google sheet accepts requests, but needs a way to differentiate approved requests, and notify members about their status. In addition, the web app ideally has a sheet view that only contains approved members, which makes it easier for data display.

![image](https://github.com/DSSD-Madison/HHI/assets/85135277/d132423d-512d-4832-9732-686331bb5a20)

### TODO
- [x] Implement Google Sheet approval system that sends an email on accept/reject. Upon rejection, it should send an email with the reason for the rejection in the comments
- [ ] Add separate view to existing Google Sheet to filter for all approved stakeholders. Should update upon approval/rejection
- [ ] Add geocoordinate lookup/conversions for the sheet entries, which include the headquarter location and locations served
- [ ] Integrate changes with #3 and #6 to connect a standardized Sheet structure via the Google Sheets API

### Resources
Google Sheet itself: https://docs.google.com/spreadsheets/d/1TI0WNrGsTKC_lZPXhcwxK4fHsc2-A88GysVtidI75z0/edit#gid=0

How to send emails through App Script: https://mailtrap.io/blog/send-emails-from-google-sheet/

Creating filters: https://support.google.com/docs/answer/3540681?hl=en&co=GENIE.Platform%3DDesktop

**Comment by GeoffreyXue** [comment]
@Rishit-5 I'll look into TODOing the Approved filtering to keep this issue moving foward, I think the scope of the first function has increased a bit with the comment

**Comment by GeoffreyXue** [comment]
Completed with https://github.com/DSSD-Madison/HHI-appscript
