### ISSUE TITLE
Feature: Reset Button Functionality

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#2]
Brief: Should require a bit of tinkering with React Leaflet, but shouldn't be too different to position + make button interactable. Estimated time ~1-2 hours

### Current State
One of the features requested on the MOU is to be able to reset the map zoom and recenter after a particular area is highlighted. 

### TODO
- [ ] Keep track of a variable when we perform a zoom in (this can be a button off the map for now, or you can set it when a particular zoom is achieved)
- [ ] Show a Reset button on the map after the variable is set to true
- [ ] When the button is clicked, the map should zoom out to a standard zoom level.
