### ISSUE TITLE
Geocode for Countries/Communities Served

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#22]
### Current State
Geocoding works for single location. The Communities/Countrie Served column still needs that functionality

### TODO
- [x] Add geocoding function to convert semicolon deliminted cell into multiple locations, semicolon delimited
- [x] Add form validation for geocoding 
- [x] Add error check for geocoding function -> Send email if location was ungeocodable
