### ISSUE TITLE
Add Site customization 

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#23]
### Current State

The current site does not have a related logo or title on the site. It also doesn't have the desired basemap for the  map.

### TODO

- [ ] Find a lighter, less contrast basemaps that complements the markers well
- [ ] Find logo and adjust title for app project
- [ ] (Stretch) If possible, find better markers for the stakeholders

**Comment by GeoffreyXue** [comment]
@MaxMaeder Update to the logo: Choose between these two logos instead. I think we can just add both to the site for now, where we can visualize one or the other based on light/dark theme, but just displaying one is fine for now.

Also while you're working on uploading the image - is it possible to also look into the broken markers as well? Appreciate it!

![Atrocity Prevention Lab_White](https://github.com/DSSD-Madison/HHI/assets/85135277/1f66b48c-eeb6-416a-bdc5-9903f7ae1a0a)
![Atrocity Prevention Lab_Black](https://github.com/DSSD-Madison/HHI/assets/85135277/5f1e8d5e-3740-4dd4-a38a-b8f51df95233)
