### ISSUE TITLE
Feature: Stakeholder Modal/Panel

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#3]
Brief: Somewhat open ended question in terms of how to implement, but throwing all the data on there + formatting should be relatively straightforward. Estimated ~2-4 hours. Adding highlighting on sheet may require considerably more time, ~+ 2hours?
 
### Current state
Leaflet maps allow for simple markers, but as requested on the MOU, interacting with a marker should provide information about one of the stakeholders for the program. The marker will locate the HQ or a known location, and information should be displayed on a modal or a panel. This information includes:
- Logo
- Name
- Link to website
- Noting countries where they operate.
- Descriptive blurb
- Tags

### TODO
- [ ] Determine what type of UI we want to use (modal, panel, something else)
- [ ] Construct single marker anywhere on map. On click, it should display the information hardcoded in the project as a panel or a modal.
- [ ] One of the extended features requested would be to click on a marker, and then highlighting all of the countries where that HQ has impact. See if you can add a list of countries/polygons to the hardcoded information, and then highlight the selected areas.

**Comment by GeoffreyXue** [comment]
Sheet with sample data:
https://docs.google.com/spreadsheets/d/1TI0WNrGsTKC_lZPXhcwxK4fHsc2-A88GysVtidI75z0/edit#gid=1940570428

**Comment by GeoffreyXue** [comment]
Email Address -> string
Organization Name -> string
Headquarter Location -> string
Headerquarter Coordinates -> tuple(float, float) (long, lat)
Countries/Communities Served -> string[]
Countries/Communities Served Coordinates -> tuple(float, float)[] (long, lat)
Desscriptive Blurb -> string
Tags/themes -> string[]
Website -> string

**Comment by GeoffreyXue** [comment]
```json
{
  "Email Address": "example@example.com",
  "Organization Name": "Sample Organization",
  "Headquarter Location": "Sample City, Sample Country",
  "Headquarter Coordinates": {
    "longitude": 12.345678,
    "latitude": 45.678901
  },
  "Countries/Communities Served": ["Community A", "Community B", "Country X"],
  "Countries/Communities Served Coordinates": [
    {"longitude": 11.111111, "latitude": 44.444444},
    {"longitude": 22.222222, "latitude": 33.333333},
    {"longitude": 55.555555, "latitude": 66.666666}
  ],
  "Descriptive Blurb": "A non-profit organization dedicated to making a positive impact in communities and countries around the world.",
  "Tags/themes": ["Education", "Healthcare", "Sustainability"],
  "Website": "https://www.sampleorganization.org"
}

```

**Comment by GeoffreyXue** [comment]
Actual list: https://docs.google.com/spreadsheets/d/1x-6w3TTQL0QJOj9Ivb1QMOUZCxG-XoNXM2yrOnRA8nY/edit#gid=2012094262
