### ISSUE TITLE
Scope Adjust: Field renaming

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#36]
Some organizations don't have a headquarter location, and are fully remote. 
Some organizations don't really have an organization email, and may have that sort of contact set up on a website. 
Also, the locations/communities served is a bit ambiguous. Replace this just with locationsServed instead

### TODOs
- [x] Change headquarter location display to headquarter location/registered location
- [x] Change organization email to be "contact" field, which can either contain an email or a website
- [x] Replace locations/communities served with just locationsServed

**Comment by GeoffreyXue** [comment]
Two PRs open, should be ready for review
