### ISSUE TITLE
Feature: Search Control Styling, Styling Standardization

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#41]
### Current State
Currently, the search icon still uses its own css styling, making it harder to standardize styling for the search control. In addition, there are some minor styling discrepancies between the controls that we could attempt to fix (borders, shadowing, etc.)

### TODO
- [ ] Bring in official Harvard colors and typography (see comment)
- [ ] Whether through tailwind, adding your own styles, or rolling a new control, attempt to standardize styling on the search control to match the existing controls
- [ ] Investigate existing controls, determine differences, standardize border, shadow, color, etc.

Note: This feature should not have to deal with mobile responsiveness; #45 will cover the development for that.

**Comment by GeoffreyXue** [comment]
@MaxMaeder Harvard actually does have a Communications Guide, which defines Harvard's typography and colors to use. We should bring these new fonts in as part of the map and also reconfigure our tailwind to include these colors for future use.
