### ISSUE TITLE
Feature: Responsive Design

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#45]
### Current State

Some parts of the map does scale. Text, however, does not scale depending on the screen size. The sidebar is also statically sized within the window. More testing is needed to be done to determine the full extent of changes

###  TODOs

- [x] Investigate and play around with app on various mobile screens. Determine components and text that need to respond dynamically
- [x] Determine standard for text size for certain screen widths. Add standardized sizes via Tailwind
- [x] Complete remaining dynamic component sizing, for each component, as necessary

**Comment by AidenCohen31** [comment]
Reviewed new code and am currently changing sidebar height and width, and considering moving the logo when in mobile development. Adding breakpoints in the css at 4k, 1080p, and mobile sizes
