### ISSUE TITLE
Update Markers, add Legend

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#48]
### Current State
The current markers on the map are pretty limited - there is only one black marker, and the locations served for each stakeholder is represented by a black circle.

The current markers are also not reactive, in the sense that the selected stakeholder marker is indistinguishable from others. This may lead to some confusion - for example, when searching a stakeholder that has a global presence, the map zooms out to the maximum zoom with no distinction between any of the markers.

### TODO
- [x] Find a way to represent a selected marker
~~- [ ] Find a suitable replacement for the black circle~~
- [x] Add a legend to distinguish between HQ/places served
- [ ] Remove black circle from legend for now

**Comment by GeoffreyXue** [comment]
This could be a nice resource: https://medium.com/trabe/creating-a-react-leaflet-custom-component-using-hooks-5b5b905d5a01

**Comment by GeoffreyXue** [comment]
@Rishit-5 Updated this issue. Per request from HHI, we will be disabling the black circles, or locations served dots, from the map for now. As a result, we can just exclude these black circles from the legend, and just use the legend for markers + the selected marker
