### ISSUE TITLE
Feature: Disable Locations Served Stakeholder markers 

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#56]
### TODOs
Per request, we will be disabling the locations/communitie served black dots for now. To ensure that this feature is still transferrable, we can just use a flag (or a boolean value) on the component to show/hide this functionality, then set it to false.

- [ ] Add boolean flag to the StakeholderLayer to prevent functionality of anything related to locations/communities served
    - [ ] Apperance on map
    - [ ] Zoom bounds (can set it to a fixed number when the flag is false for now)
- [ ] Set the boolean flag to false
