### ISSUE TITLE
Feature: Google Sheets API Integration

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#6]
Brief: Not open ended, straightforward step by step. Must also include key for deployment and set up process. Implementation time ~1-3 hours

### Current State
As mentioned in #1, we'll be using Google Sheets with a Form to act as a way for stakeholders to submit their permissions, and also for the HHI team to review these submissions. The general concept for now for "accepting is" to take a submission, and move it to an "accepted" sheet area.

### TODO
- [x] Figure out necessary setup for Google Sheets API
- [x] Add API secret/key/whatever to project safely, also add it to the deployment process.
- [x] Share key with rest of team somewhere/somehow so others can use this during development
- [x] (Stretch) Look into location conversion via an API, also potentially more thorough validation on the sheet itself.

**Comment by GeoffreyXue** [comment]
This has significant crossover with the RVAGreen logic. I'll share some of the logic done for that on here in a bit.

@GeoffreyXue

**Comment by GeoffreyXue** [comment]
Spreadsheet to work with: https://docs.google.com/spreadsheets/d/1TI0WNrGsTKC_lZPXhcwxK4fHsc2-A88GysVtidI75z0/edit#gid=0
