### ISSUE TITLE
Feature: Github Pages Deployment

### ISSUE THREAD

**Issue by GeoffreyXue** [DSSD-Madison/HHI#63]
As part of the request, we'll be switching from Netlify deployments to instead using Github Pages with a Github Action (on PR into main).

### TODOs
- [x] Set up Github Action
- [x] Set appropriate secrets
- [x] (Optional) -> Look into potential ways to keep a dev branch running for PRs

### Context

This app is uses Vite to build out the Typescript/React project, which is a fairly common setup. This means there likely are some samples/implementations of github actions out there in the wild already.

**Comment by GeoffreyXue** [comment]
(Potentially) Useful Resources

Vite deploy potentially: https://github.com/sitek94/vite-deploy-demo

Dev Branch PR: https://stackoverflow.com/questions/32629223/github-pages-dev-branch
